### ISSUE TITLE
windows登录进去白屏

### ISSUE THREAD

**Issue by ljw-codeking** [wenqiyun/nest-admin#15]
node： 14.18.1
系统：windows
账号：admin/admin
接口：http://localhost:9540/api/perm/menu
菜单返回为空数组
![image](https://user-images.githubusercontent.com/75002215/158957229-a6a02f45-e3e8-4d1e-8457-2e6dc650b96f.png)

**Comment by wenqiyun** [comment]
需要在数据库配置初始权限，先引入 db文件夹中的 sql 文件

**Comment by 1103409364** [comment]
前端部分考虑用vite吗？

**Comment by wenqiyun** [comment]
> 前端部分考虑用vite吗？

暂时还没考虑
