### ISSUE TITLE
nest-redis有新替代方案了

### ISSUE THREAD

**Issue by z851103999** [wenqiyun/nest-admin#18]
@liaoliaots/nestjs-redis

**Comment by z851103999** [comment]
就是有一个缺点，好像config不能用，好像不支持从config.yaml去调用redis密码什么的。

**Comment by wenqiyun** [comment]
> 就是有一个缺点，好像config不能用，好像不支持从config.yaml去调用redis密码什么的。

我去看看

**Comment by wenqiyun** [comment]
项目 已切换 @liaoliaots/nestjs-redis

**Comment by hardwin1014** [comment]
> 项目 已切换 @liaoliots/nestjs-redis

@nestjs/common@10.2.5和@liaoliaots/nestjs-redis@9.0.5又有冲突了，导致npm i下载失败

**Comment by hardwin1014** [comment]
> 项目已切换@liaoliots/nestjs-redis

使用yarn就没事
