### ISSUE TITLE
If ModuleRef is a provider, is it part of the current RedisCoreModule?

### ISSUE THREAD

**Issue by CloudWoR** [wenqiyun/nest-admin#20]
nestjs-redis的仓库是不是更新了代码？首先是pnpm无法下载，然后直接下载nestjs-redis后，发现无法使用，报这个错：
`If ModuleRef is a provider, is it part of the current RedisCoreModule?`
这个错我在redisCoreModule里面不知道如何修改呀。
`- If ModuleRef is a provider, is it part of the current RedisCoreModule?
- If ModuleRef is exported from a separate @Module, is that module imported within RedisCoreModule?
  @Module({
    imports: [ /* the Module containing ModuleRef */ ]
  })`
请问这个该如何解决？

**Comment by CloudWoR** [comment]
按照issues里面的方法，改成了1.28版本，也不行哦。

**Comment by gslnzfq** [comment]
修改代码，使用"@liaoliaots/nestjs-redis": "^8.1.0"可以解决

**Comment by wenqiyun** [comment]
单独使用 npm/pnpm i <nestjs-redis git 地址> 安装一次，如果 github 很难下载成功，可以用 gitee 同步官方库到自己的仓库下载
