### ISSUE TITLE
、

### ISSUE THREAD

**Issue by CloudWoR** [wenqiyun/nest-admin#21]
nestjs-redis的仓库是不是更新了代码？首先是pnpm无法下载，然后直接下载nestjs-redis后，发现无法使用，报这个错：
`If ModuleRef is a provider, is it part of the current RedisCoreModule?`
这个错我在redisCoreModule里面不知道如何修改呀。
`- If ModuleRef is a provider, is it part of the current RedisCoreModule?
- If ModuleRef is exported from a separate @Module, is that module imported within RedisCoreModule?
  @Module({
    imports: [ /* the Module containing ModuleRef */ ]
  })`
请问这个该如何解决？

**Comment by wenqiyun** [comment]
新版已解决该问题
