### ISSUE TITLE
新增账户绑定角色关系（所有路由全选）；用新账户登陆，权限菜单（perm/menu）接口返回数据 为空数组

### ISSUE THREAD

**Issue by waybacktolove** [wenqiyun/nest-admin#45]

**Comment by waybacktolove** [comment]
新账户，info接口返回数据如下`{
  "id": "3",
  "account": "test1",
  "phoneNum": "1834754658",
  "email": "123@mal.com",
  "status": 1,
  "avatar": "http://localhost:8081/static/67f57d2058984103afc54d164aff5648.jpeg",
  "type": 1,
  "createDate": "2023-02-12T01:56:50.000Z",
  "updateDate": "2023-02-12T01:56:50.000Z"
}`

**Comment by wenqiyun** [comment]
新账号是不是登录过，登录之后，再去配置权限，需要等一个缓存周期，新配置的权限才会生效

**Comment by wenqiyun** [comment]
已支持权限设置后，立即生效

**Comment by thl3538** [comment]
> 新账号是不是登录过，登录之后，再去配置权限，需要等一个缓存周期，新配置的权限才会生效

你好，这个再去配置权限是如何配置呢
