### ISSUE TITLE
辛苦作者了，跟了一遍，发现了一些小bug

### ISSUE THREAD

**Issue by langren1353** [wenqiyun/nest-admin#47]
## 前端代码
1. 登录后，复制网址，新开tab，会再次要求登录，我看代码是用sessionStorage存储的，不知道是不是有什么特别的想法
2. 两个项目的eslint好像都有些问题，不过能用
3. 上传功能似乎没有推代码
4. 用户权限管理Edit那里列表似乎应该用allMenu
5. perm.ts:27左右的白名单校验规则似乎要全匹配，所以带参数的也无法通过

## 后端代码
1. 部分Service中的getManager写法已经deprecated了，我这里遇到了报错，改成对应的dataSource.manager就行了

很不错的demo，我新人，拿来学习学习nestjs挺好的，感谢作者

**Comment by langren1353** [comment]
前端：角色编辑的时候RoleMenuTree中model的更新&获取，会导致watch彼此冲突

**Comment by wenqiyun** [comment]
感谢体验，目前打算用 vite 重写前端，修复一些 bug 如果有兴趣可以加群 
![Screenshot_2023-03-09-14-15-00-449_com tencent mm-edit](https://user-images.githubusercontent.com/26480805/223936526-b02fb2e3-8c83-473a-8d93-dec042137732.jpg)
