### ISSUE TITLE
TypeError: layout is not a function

### ISSUE THREAD

**Issue by bulolo** [wenqiyun/nest-admin#5]
![image](https://user-images.githubusercontent.com/10026498/111314384-512f3300-869c-11eb-8c67-ac46722c4503.png)
登录时候 报这个错

**Comment by bulolo** [comment]
实在太多问题了吧。。。把log4js去掉后，还是一堆问题。希望能更新下。

**Comment by zamlia** [comment]
我也是这个问题

**Comment by Lance-Mao** [comment]
这个问题有人知道怎么解决没

**Comment by wenqiyun** [comment]
![image](https://user-images.githubusercontent.com/26480805/127123216-946d2b95-03dd-4286-9e51-3991640fd59c.png)
servers/src/common/utils/log.util.ts 删除图片圈中的代码

**Comment by wenqiyun** [comment]
> 这个问题有人知道怎么解决没

https://github.com/wenqiyun/nest-admin/issues/5#issuecomment-887323095

**Comment by wenqiyun** [comment]
> 我也是这个问题

https://github.com/wenqiyun/nest-admin/issues/5#issuecomment-887323095

**Comment by Lance-Mao** [comment]
![image](https://user-images.githubusercontent.com/26965644/131065371-3d2aa921-1ad0-40bf-a37a-959bcdff8957.png)
![image](https://user-images.githubusercontent.com/26965644/131065406-914a3cfc-6f77-4c7e-b42e-ecbc8e5965a9.png)
把这块抽出来，能解决这个问题

**Comment by Lance-Mao** [comment]
这个项目权限也没有做好，权限校验还有问题，当初没有仔细看，结果就直接拿来用了，坑太多了

**Comment by Lance-Mao** [comment]
![image](https://user-images.githubusercontent.com/26965644/131068800-ce90e3ee-ac71-4ed7-bd07-fb255406e1b2.png)
能解释下这里为啥需要加localStorage，服务端的jwt过期了，这个好像永远都不会过期，所以服务端过期了，也不会跳到登录页面

**Comment by Lance-Mao** [comment]
![image](https://user-images.githubusercontent.com/26965644/131070030-24d10124-2628-4da0-81ce-fb72097fe6a2.png)
这三个方法，直接这么写不行吗

**Comment by wenqiyun** [comment]
> ![image](https://user-images.githubusercontent.com/26965644/131068800-ce90e3ee-ac71-4ed7-bd07-fb255406e1b2.png)
> 能解释下这里为啥需要加localStorage，服务端的jwt过期了，这个好像永远都不会过期，所以服务端过期了，也不会跳到登录页面

**Comment by wenqiyun** [comment]
> ![image](https://user-images.githubusercontent.com/26965644/131068800-ce90e3ee-ac71-4ed7-bd07-fb255406e1b2.png)
> 能解释下这里为啥需要加localStorage，服务端的jwt过期了，这个好像永远都不会过期，所以服务端过期了，也不会跳到登录页面

这个地方使用 cookie  定义一个 首次获取 token 的时间戳，localStorage 存储 token 的具体值

**Comment by wenqiyun** [comment]
> ![image](https://user-images.githubusercontent.com/26965644/131070030-24d10124-2628-4da0-81ce-fb72097fe6a2.png)
> 这三个方法，直接这么写不行吗

可以这样写，这边没有这么写是因为，token 比较长 ，存 cookie 每个请求 包含静态图片请求都会带 cookie ，比较耗带宽
