### ISSUE TITLE
运行项目后,  访问地址提示 layout is not a function

### ISSUE THREAD

**Issue by wodabo** [wenqiyun/nest-admin#8]
![1637133125(1)](https://user-images.githubusercontent.com/25549797/142151479-d5576bb2-aa2e-45f4-bc94-433ff1ad0596.jpg)

node版本 12, 16都试过

**Comment by wenqiyun** [comment]
在这条已解决代码中未修改，https://github.com/wenqiyun/nest-admin/issues/5#issuecomment-887323095

**Comment by wenqiyun** [comment]
目前正在积极开发v2版本，v1版本暂不修复，可以参考 https://github.com/wenqiyun/nest-admin/issues/5#issuecomment-887323095 报错修复
